services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=iam'
      - 'POSTGRES_PASSWORD=secret'
      - 'POSTGRES_USER=myuser'
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./src/main/resources/db/init:/docker-entrypoint-initdb.d:ro
  redis:
    image: 'redis:latest'
    ports:
      - '6379:6379'

volumes:
  postgres-data: