spring:
  application:
    name: iam-basic
  datasource:
    url: jdbc:postgresql://localhost:5432/iam
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init/schema.sql
#      data-locations: classpath:db/init/data.sql
      platform: PostgreSQL
      continue-on-error: true
      encoding: UTF-8
      separator: ;

iam:
  security:
    jwt:
      issuer: "https://iam.guangyiliushan.top"
      secret: "dGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIHNlY3JldCBrZXk=" # 必须是 Base64 编码的字符串，长度至少 32 字节 (HS256)
      key-id: "identity-hs-kid"
      mac-algorithm: HS256
      access-token:
        audience: "iam-api"
        ttl: 15m
        type: "at+jwt"
      refresh-token:
        audience: "iam-refresh"
        ttl: 30d
        type: "rt+jwt"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

snowflake:
  worker-id: 1
  datacenter-id: 1
