spring:
  application:
    name: iam-basic
  datasource:
    url: jdbc:postgresql://localhost:5432/iam
    username: myuser
    password: secret
    driver-class-name: org.postgresql.Driver
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: UTC
    show-sql: false
  sql:
    init:
      mode: always
      schema-locations: classpath:db/init/schema.sql
#      data-locations: classpath:db/init/data.sql
      platform: PostgreSQL
      continue-on-error: true
      encoding: UTF-8
      separator: ;

iam:
  security:
    jwt:
      issuer: "https://iam.guangyiliushan.top"
      client-id: "iam-basic"
      signing:
        active-key-id: "identity-hs-kid"
        keys:
          - id: "identity-hs-kid"
            type: HS
            mac-algorithm: HS256
            secret: "dGhpcyBpcyBhIHZlcnkgc2VjdXJlIGFuZCBsb25nIHNlY3JldCBrZXk="
      access-token:
        audience: "iam-api"
        ttl: 15m
        type: "at+jwt"
      refresh-token:
        audience: "iam-refresh"
        ttl: 30d
        type: "rt+jwt"
      session:
        max-concurrent-sessions: 5
      refresh-token-cookie:
        name: "IAM_REFRESH_TOKEN"
        path: "/api/iam/refresh"
        http-only: true
        secure: true
        same-site: STRICT
        max-age: 30d

  identity:
    cache:
      redis:
        reuse-marker-ttl-floor: 1s
        unlink-enabled: true

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true

snowflake:
  worker-id: 1
  datacenter-id: 1
